baseURL = "https://flaxandteal.co.uk/"
languageCode = "en-us"
title = "Flax &amp; Teal"
publishDir = "docs"
sectionPagesMain = "main"
relativeURLs = true

[markup]
  [markup.goldmark.renderer]
       unsafe=true
